site_name: German Notebook
site_url: https://example.com/
nav:
  - Home: index.md
  - Grammar:
    - Basic Grammar: grammar/basics.md
  - Dictionary:
    - Nouns: vocabulary/nouns.md
    - Verbs: vocabulary/verbs.md
    - Numbers: vocabulary/numbers.md
    - Pronouns: vocabulary/pronouns.md
    - Adverbs: vocabulary/adverbs.md

# theme: simple-blog
# theme: readthedocs
# theme: material - has search
# theme: windmill-dark - has search
## Set name attribute below with one of above themes
theme:
  name: simple-blog
  features:
    - search.suggest
  include_search_page: true
  search_index_only: true


plugins:
  - search