site_name: German Notebook
site_url: https://example.com/
nav:
  - Home: index.md
  - Grammar:
    - Basic Grammar: grammar/basics.md
  - Vocabulary:
    - Category 1: vocabulary/category1.md

# theme: simple-blog
# theme: readthedocs
# theme: material - has search
# theme: windmill-dark - has search
theme:
  name: simple-blog
  features:
    - search.suggest
  include_search_page: true
  search_index_only: true


plugins:
  - search